### ISSUE TITLE
projects/vue-quill-editor/nuxt/editor.vue中的mounted方法有错误

### ISSUE THREAD

**Issue by dong-king** [surmon-china/surmon-china.github.io#1]
```
mounted() {
      console.log('App init, the Quill instance object is:', this.editor.quill)
      setTimeout(() => {
        this.content = 'I was changed!'
      }, 3000)
    },
````
在mounted中的this.editor是undefined，但是使用this.$refs.editor也会是undefined。应该是使用了client-only标签包裹，导致在mounted中还看不到this.$refs.editor

**Comment by surmon-china** [comment]
`mounted` 是一个 server & client 都会执行的 hook，所以服务端时确实不会存在的。

**Comment by dong-king** [comment]
@surmon-china 
我尝试在mounted()中增加process.client的判断，但是还是存在这个问题。
```
mounted() {
      if (process.client) {
          console.log('App init, the Quill instance object is:', this.editor.quill);
      }
      setTimeout(() => {
        this.content = 'I was changed!'
      }, 3000)
    },
```

但是我把template中的client-only标签去掉，则在mounted()中可以看到this.$refs.editor不再是一个undefined了。
但是去了client-only的标签又会提示warning：
The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

**Comment by surmon-china** [comment]
你的需求既与周期有强关系，则应使消费逻辑关注周期。

所以你的需求需要确保一件事：保证任何对于 Quill 实例的消费，都在 Quill 实例已确定发生之后。

1. 可以用 ready 事件
2. 使用 watch (compouted -> this.$refs.editor.quill)
3. 使 Quill 成为一个单独的组件，在组件内部 `do something when mounted`，外部用 `<client-only>` 控制。
---

实际上我发现是代码错了，`this.editor` 确实是个不存在的东西，应该是 `this.$refs.editor`，谢谢你认真的测试。

**Comment by dong-king** [comment]
@surmon-china 
我刚注意到，你的vue-quill-editor有更新，现在的这个nuxt下的example应该是按照最新vue-quill-edittor进行测试的。
因为我是通过npm安装的vue-quill-editor@3.0.6，然后又按照你这个nuxt下的example写的代码。这两者之间应该有点不匹配。

**Comment by surmon-china** [comment]
示例代码是新写的，但是基本一致，应该没有不兼容，`vue-quill-editor` 暂时还没有已发布的新版本。

**Comment by surmon-china** [comment]
文件已更新。
