### ISSUE TITLE
why was not found module

### ISSUE THREAD

**Issue by lemonchip** [surmon-china/surmon-china.github.io#2]
ERROR  Failed to compile with 1 errors                                                                                  friendly-errors 16:27:14  

This relative module was not found:                                                                                      friendly-errors 16:27:14  
                                                                                                                         friendly-errors 16:27:14  
* ./editor.vue?vue&type=style&index=0&id=db7b56b4&lang=scss&scoped=true& in ./pages/editor.vue                           friendly-errors 16:27:14  
i Waiting for file changes

**Comment by surmon-china** [comment]
What's `./editor.vue`?
