### ISSUE TITLE
Cannot resolve "swiper/css/swiper.css"

### ISSUE THREAD

**Issue by BruceFeng518** [surmon-china/surmon-china.github.io#4]
(node:9196) UnhandledPromiseRejectionWarning: Error: Could not compile template E:\\bruce\\cp\\node_modules\\@nuxt\\vue-app\\template\\App.js: Cannot resolve "swiper/css/swiper.css" from "E:\bruce\cp\swiper\css\swiper.css"
    at E:\bruce\cp\node_modules\@nuxt\builder\dist\builder.js:6018:17
    at async Promise.all (index 0)
    at async Builder.compileTemplates (E:\bruce\cp\node_modules\@nuxt\builder\dist\builder.js:5996:5)
    at async Builder.generateRoutesAndFiles (E:\bruce\cp\node_modules\@nuxt\builder\dist\builder.js:5682:5)
    at async Builder.build (E:\bruce\cp\node_modules\@nuxt\builder\dist\builder.js:5594:5)
    at async start (E:\bruce\cp\server\index.js:24:5)
(node:9196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[nodemon] clean exit - waiting for changes before restart

**Comment by surmon-china** [comment]
`E:\bruce\cp\swiper\css\swiper.css` ?

**Comment by BruceFeng518** [comment]
我新建一个项目，按照教程安装，报这个错误，之前spa单页面可以，换了ssr 之后总错，是什么原因呢

**Comment by BruceFeng518** [comment]
SSR example code 可否详细点

**Comment by surmon-china** [comment]
1. 检查你的 Swiper 是否单独安装，4.x 中的 Swiper 为 `peerDependencie`，README 中都有表述
2. Example code 已经没有更细的余地
3. 具体项目有关的（非此演示项目本身的问题）问题去对应的目标项目下提 Issue
